# Generated by Django 4.1.5 on 2023-01-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_remove_students_family_l_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='grade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
