# Generated by Django 4.1.5 on 2023-01-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_students_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='family_l_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='family_m_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='family_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
