# Generated by Django 4.1.5 on 2023-02-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0017_students_family_city_students_family_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='age',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffs',
            name='level',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffs',
            name='phone_no',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffs',
            name='sex',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
