# Generated by Django 4.1.5 on 2023-02-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0020_rename_family_l_name_students_first_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='section',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
