# Generated by Django 4.1.5 on 2023-02-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0021_students_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_num',
            field=models.IntegerField(default=0),
        ),
    ]
