# Generated by Django 4.1.5 on 2023-02-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0023_alter_students_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='section',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
