# Generated by Django 4.1.5 on 2023-02-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0025_section_cou_sec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=10),
        ),
    ]
