# Generated by Django 4.1.5 on 2023-01-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_studentactivate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_type', models.BooleanField(default=False)),
            ],
        ),
    ]
