# Generated by Django 4.1.5 on 2023-01-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_logintype'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='mother',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
