# Generated by Django 4.1.5 on 2023-01-31 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_students_mother'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='mother',
        ),
    ]
