# Generated by Django 4.1.5 on 2023-01-31 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_remove_students_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='family_l_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='family_m_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='students',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='students',
            name='relation',
        ),
    ]
