# Generated by Django 4.1.5 on 2023-01-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_students_family_l_name_students_family_m_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='grade',
            new_name='family_adress',
        ),
        migrations.AddField(
            model_name='students',
            name='phone_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='relation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
