# Generated by Django 4.1.5 on 2023-02-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0016_rename_grade_students_family_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='family_city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='family_phone_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
