# Generated by Django 4.1.5 on 2023-02-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0018_staffs_age_staffs_level_staffs_phone_no_staffs_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintype',
            name='activate_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logintype',
            name='insert_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logintype',
            name='result_type',
            field=models.BooleanField(default=False),
        ),
    ]
