# Generated by Django 4.1.5 on 2023-02-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0022_courses_course_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
