# Generated by Django 4.1.5 on 2023-02-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0024_subjects_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(default='A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='cou_sec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=40)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.section')),
            ],
        ),
    ]
